### ISSUE TITLE
function_link matches everything until the next closed parenthesis

### ISSUE THREAD

**Issue by fargiolas** [tree-sitter-grammars/tree-sitter-doxygen#11]
It seems that function_link pattern is a bit fragile if the opening parenthesis is not closed as expected.
In particular it matches multiple lines and eats up other tags. Here's an emacs screenshot showing the problem.

<img width="350" alt="emacs-ts-doxy" src="https://github.com/tree-sitter-grammars/tree-sitter-doxygen/assets/133750/31f2d78e-4e8b-4977-8ad2-d45abe410c4e">

I guess it would be better to either stop at new line (not sure if doxygen autolink matches function names on multiple lines) or maybe at the next '@' or '\\' tag instead of blindly matching from one parenthesis to the next no matter what's in between.

**Comment by amaanq** [comment]
I have no clue either, but I agree it'd be a better experience to have it not over-consume across multiple lines, this is fixed now
