### ISSUE TITLE
`in` displays incorrectly in `\brief`

### ISSUE THREAD

**Issue by MarcelRobitaille** [tree-sitter-grammars/tree-sitter-doxygen#9]
I have a comment like `//! \brief Blah blah blah in case blah blah blah`. The word `in` is showing in yellow just like the `in` in `\param[in]`. 

Interestingly, I can't see anything in the treesitter playground. Only:
```
      comment [780, 0] - [780, 88]
        tag_name [780, 4] - [780, 10]
```

Here is the result of `:Inspect` with my cursor on `in`.
```
Treesitter
  - @comment.cpp links to Comment cpp
  - @spell.cpp links to @spell cpp
  - @storageclass.doxygen links to StorageClass doxygen
```

Another interesting thing is that I've only noticed this for `\brief`. It doesn't happen for `\note`, `\return`, or `\param` (after the first `[in]`, of course).

**Comment by amaanq** [comment]
I cannot reproduce with your code I would need some more context or information

**Comment by amaanq** [comment]
Oh wait - I didn't support single-line comments, did you add a query yourself to do that? That might be why

**Comment by MarcelRobitaille** [comment]
You're right, I did, but I can still reproduce it even if I revert those changes. As you can see, the `//!` style comment is not getting any highlighting. Right is Treesitter playground and bottom is `:Inspect` with my cursor on `in` in the first line.
![image](https://github.com/amaanq/tree-sitter-doxygen/assets/8503756/9aa98b44-4db4-4dee-a428-55543b2adc93)

For this I `cd`ed into `/tmp` and made this simple `main.cpp`. I will try with a more minimal vim configuration.

**Comment by MarcelRobitaille** [comment]
@amaanq BTW, may I ask why you don't support `//! ` comments? This is the convention where I work.

**Comment by amaanq** [comment]
I'd only be able to parse *one* comment line - you cannot combine a bunch of sequential comments as one node in any of the languages that use Doxygen

If that's worth it to you (your Doxygen blocks span one comment at a time) then let me know and I'll see about supporting it or feel free to submit a PR

**Comment by MarcelRobitaille** [comment]
@amaanq What would the consequence be exactly? I'm interested in syntax highlighting for something like the following:

```cpp
//! \brief The function does x y z
//! \param[in] arg This argument controls something
```

Even considering one line at a time, I would expect it to work, wouldn't it? The param should be highlighted even without `//! \brief`.

Does it just mean that 
```cpp
//! \return \c
//! true
```
would not highlight `true` correctly for example?
